apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-quarkus
spec:
  selector:
    matchLabels:
      app: operator-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: operator-quarkus
    spec:
      serviceAccountName: operator-quarkus
      containers:
        - image: $INTERNAL_IMAGE_REPO/$DUMMY_DEPLOY_NAMESPACE/operator-quarkus:1.0-SNAPSHOT
          name: operator-quarkus
          imagePullPolicy: IfNotPresent
